version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - API_KEY=${GUARDIAN_API_KEY}
